<a href="https://colab.research.google.com/github/nyongja/basic-of-reinforcement-learning/blob/main/Q_Table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gym

In [2]:
!pip install tensorflow==1.14

     |████████████████████████████████| 109.2MB 87kB/s 
     |████████████████████████████████| 3.2MB 59.7MB/s 
     |████████████████████████████████| 51kB 3.5MB/s 
     |████████████████████████████████| 491kB 50.1MB/s 
  Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninstalled tensorboard-2.4.1
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1


In [3]:
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
env = gym.make('FrozenLake-v0')

## Q 테이블 학습 알고리즘 구현

In [32]:
# 테이블을 모두 0으로 초기화한다.
Q = np.zeros([env.observation_space.n, env.action_space.n])
# 학습 매개변수를 설정한다.
lr = .85
y = .99
num_episodes = 2000
# 보상의 층계를 담을 리스트를 생성한다.
rList = []
for i in range(num_episodes) :
  # 환경을 리셋하고 첫 번째 새로운 관찰을 얻는다.
  s = env.reset()
  rAll = 0
  d = False
  j = 0
  # Q 테이블 학습 알고리즘
  while j < 99 :
    j += 1
    # Q 테이블로부터 (노이즈와 함께) 그리디하게 액션을 선택
    a = np.argmax(Q[s, :] + np.random.randn(1, env.action_space.n) * (1. / (i+1)))
    # 환경으로부터 새로운 상태와 보상을 얻는다.
    s1, r, d, _ = env.step(a)
    # 새로운 지식을 통해 Q 테이블을 업데이트한다.
    Q[s, a] = Q[s, a] + lr * (r + y * np.max(Q[s1, :]) - Q[s, a])
    rAll += r
    s = s1
    if d == True :
      break
  rList.append(rAll)

In [33]:
print("Score over time : " + str(sum(rList) / num_episodes))

Score over time : 0.3885


In [34]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[8.74525868e-03 9.26740973e-03 5.45961971e-01 1.05749848e-02]
 [1.81772635e-04 1.66397628e-03 1.33860447e-03 3.11093315e-01]
 [4.33512169e-03 4.56696290e-03 2.59479192e-03 1.44355515e-01]
 [1.78679679e-03 1.43812642e-03 1.44192533e-03 1.18595815e-01]
 [6.03363159e-01 1.22109636e-03 2.38760705e-04 9.72185518e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.93781519e-04 3.58629122e-05 1.37071034e-01 1.28856201e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.14952429e-04 1.68114892e-04 5.39202010e-03 3.70400029e-01]
 [2.46863852e-04 6.89950331e-01 1.81725598e-03 8.39875516e-04]
 [1.89043565e-01 1.85626535e-05 0.00000000e+00 1.32453438e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.40907952e-04 2.08672525e-03 9.45567713e-01 2.42866302e-03]
 [0.00000000e+00 0.00000000e+00 9.97608419e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.