<a href="https://colab.research.google.com/github/nyongja/basic-of-reinforcement-learning/blob/main/Q_Table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gym

In [2]:
!pip install tensorflow==1.14

     |████████████████████████████████| 109.2MB 50kB/s 
     |████████████████████████████████| 491kB 54.5MB/s 
     |████████████████████████████████| 51kB 6.0MB/s 
     |████████████████████████████████| 3.2MB 39.5MB/s 
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninstalled tensorboard-2.4.1
  Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1


In [3]:
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
env = gym.make('FrozenLake-v0')

## Q 테이블 학습 알고리즘 구현

In [6]:
# 테이블을 모두 0으로 초기화한다.
Q = np.zeros([env.observation_space.n, env.action_space.n])
# 학습 매개변수를 설정한다.
lr = .85
y = .99
num_episodes = 2000
# 보상의 층계를 담을 리스트를 생성한다.
rList = []
for i in range(num_episodes) :
  # 환경을 리셋하고 첫 번째 새로운 관찰을 얻는다.
  s = env.reset()
  rAll = 0
  d = False
  j = 0
  # Q 테이블 학습 알고리즘
  while j < 99 :
    j += 1
    # Q 테이블로부터 (노이즈와 함께) 그리디하게 액션을 선택
    a = np.argmax(Q[s, :] + np.random.randn(1, env.action_space.n) * (1. / (i+1)))
    # 환경으로부터 새로운 상태와 보상을 얻는다.
    s1, r, d, _ = env.step(a)
    # 새로운 지식을 통해 Q 테이블을 업데이트한다.
    Q[s, a] = Q[s, a] + lr * (r + y * np.max(Q[s1, :]) - Q[s, a])
    rAll += r
    s = s1
    if d == True :
      break
rList.append(rAll)

In [7]:
print("Score over time : " + str(sum(rList) / num_episodes))

Score over time : 0.0005


In [8]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[3.81617859e-01 4.56300724e-03 5.05936274e-03 5.51377092e-03]
 [1.47868138e-03 3.36626746e-05 2.38691516e-04 4.97799979e-01]
 [2.93269862e-03 2.88176928e-01 6.98035686e-04 2.82770109e-03]
 [2.29847262e-04 1.51680278e-03 0.00000000e+00 2.85191458e-01]
 [3.95434047e-01 0.00000000e+00 5.20598053e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.00533745e-01 1.17089540e-05 2.00155853e-05 1.67241515e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 7.04401695e-01]
 [0.00000000e+00 7.96477914e-01 0.00000000e+00 0.00000000e+00]
 [3.59656470e-01 3.46727079e-04 2.11473149e-04 4.58843914e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.60223597e-01 5.06315969e-03]
 [0.00000000e+00 0.00000000e+00 9.97632109e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.